version: "2.1"
services:
  test:
    image: python:3.6
    command: bash -c "pip install -r test-requirements.txt && python -m unittest tests.test_setup_logging tests.test_datadog_formatter"
    working_dir: /muselog
    volumes:
      - .:/muselog

  mongo:
    image: mongo:3
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    environment:
      - http.host=0.0.0.0
      # Disable X-Pack security: https://www.elastic.co/guide/en/elasticsearch/reference/5.5/security-settings.html#general-security-settings
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
  graylog:
    image: graylog/graylog:2.3.1-1
    environment:
      - GRAYLOG_PASSWORD_SECRET=wutevaidowhatiwant
      # Password: admin
      - GRAYLOG_WEB_ENDPOINT_URI=http://127.0.0.1:9000/api
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 514:514
      # Syslog UDP
      - 514:514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
